version: 2
updates:
  - package-ecosystem: nuget
    directory: "/eFormAPI"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/eform-client"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/eform-client"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    target-branch: "angular13"
    labels: "angular13 dependencies"